### ISSUE TITLE
New drone bays don't send out multiple streams

### ISSUE THREAD

**Issue by J-Aric** [Nishikawa-Technologies-Corporation/NTCED-Delta-V-Mod#10]
Multi stream drone bays don't seem to actually send out multiple streams (NTCED Dual Hybird Harvester Class (950M x2 per Hardpoint))

**Comment by RS-Chan** [comment]
Will investigate when I have time, will see if update affected anything regarding anything with the drone BUS or not.

**Comment by J-Aric** [comment]
> Will investigate when I have time, will see if update affected anything regarding anything with the drone BUS or not.

Update: Modules DO produce multiple streams, but if you have 2+ of the added modules, they seem to all target the same chunks, making it seem like only 2 streams are being produced (also causes massive drone waste and very jittery chunks)

**Comment by RS-Chan** [comment]
> > Will investigate when I have time, will see if update affected anything regarding anything with the drone BUS or not.
> 
> Update: Modules DO produce multiple streams, but if you have 2+ of the added modules, they seem to all target the same chunks, making it seem like only 2 streams are being produced (also causes massive drone waste and very jittery chunks)

What version of the mod is this? This should've been addressed with the v1.1.0 to prevent same ore targeting as per release notes.

**Comment by J-Aric** [comment]
> > > Will investigate when I have time, will see if update affected anything regarding anything with the drone BUS or not.
> > 
> > 
> > Update: Modules DO produce multiple streams, but if you have 2+ of the added modules, they seem to all target the same chunks, making it seem like only 2 streams are being produced (also causes massive drone waste and very jittery chunks)
> 
> What version of the mod is this? This should've been addressed with the v1.1.0 to prevent same ore targeting as per release notes.

V1.1.0 From nexus.
EDIT: Tested with most recent release from Gtihub, still exists

**Comment by 1-WT-1** [comment]
Just found out about this. Can confirm that multiple drone launchers target the same piece, especially if it's only one around the ship and is in the deceleration zone, causes a lot of physics lag.
 I was playing with AdvancedDrones and YeetProtocol enabled though, so next time I'll try using just NTCED and replicate this.

**Comment by RS-Chan** [comment]
> Just found out about this. Can confirm that multiple drone launchers target the same piece, especially if it's only one around the ship and is in the deceleration zone, causes a lot of physics lag. I was playing with AdvancedDrones and YeetProtocol enabled though, so next time I'll try using just NTCED and replicate this.

Thanks WT, I'm assuming one of the latest updates dealt with the drones and how it targets ores and other related items. Will need to get with Za'krin and see if there is maybe a update is needed on the AdvancedDrone's file.
